[
    <json> [https://raw.githubusercontent.com/rgchris/Scripts/master/ren-c/altjson.reb]
    <xml> [http://giuliolunati.altervista.org/r3/altxml.reb]
    <amazon-s3> [http://reb4.me/r3/s3.reb]
    <httpd> [https://raw.githubusercontent.com/rgchris/Scripts/master/ren-c/httpd.reb]
    <twitter> [https://raw.githubusercontent.com/gchiu/rebolbot/master/twitter.r3]
    <trello> [http://codeconscious.com/rebol-scripts/trello.r]
    <upgrade> [https://raw.githubusercontent.com/gchiu/rebol-misc/master/upgrade.reb]
    <rebmu> [https://raw.githubusercontent.com/hostilefork/rebmu/master/rebmu.reb]
]            
