[
    <amazon-s3> [http://reb4.me/r3/s3.reb]
    <detab-file> [https://raw.githubusercontent.com/r3n/renclib/master/scripts/detab-file]
    <html> [https://raw.githubusercontent.com/r3n/giuliolunati.renclib/master/usr/lib/r3/html.reb]
    <httpd> [https://raw.githubusercontent.com/r3n/renclib/master/modules/httpd.reb]
    <json> [https://raw.githubusercontent.com/r3n/renclib/master/modules/json.reb]
    <mysql> [https://raw.githubusercontent.com/zsx/mysql-r3/ren-c/mysql-protocol-pre.r]
    <pop3> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-pop3.reb]
    <rebmu> [https://raw.githubusercontent.com/hostilefork/rebmu/master/rebmu.reb]
    <rem> [https://raw.githubusercontent.com/r3n/giuliolunati.renclib/master/usr/lib/r3/rem.reb]
    <synctcp> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-synctcp.reb]
    <trello> [http://codeconscious.com/rebol-scripts/trello.r]
    <twitter> [https://raw.githubusercontent.com/gchiu/rebolbot/master/twitter.r3]
    <upgrade> [https://raw.githubusercontent.com/gchiu/rebol-misc/master/upgrade.reb]
    <webserver> [https://raw.githubusercontent.com/r3n/renclib/master/scripts/webserver.reb]
    <xml> [https://raw.githubusercontent.com/r3n/renclib/master/modules/xml.reb]
]            
