[
    <amazon-s3> [http://reb4.me/r3/s3.reb]
    <curl> [https://raw.githubusercontent.com/rgchris/Scripts/master/experimental/curl.reb]
    <dl-renc> [https://raw.githubusercontent.com/gchiu/Rebol3/master/scripts/dl-renc.reb]
    <html> [https://raw.githubusercontent.com/r3n/giuliolunati.renclib/master/usr/lib/r3/html.reb]
    <httpd> [https://raw.githubusercontent.com/r3n/renclib/master/outdated/modules/httpd.reb]
    <json> [https://raw.githubusercontent.com/r3n/renclib/master/outdated/modules/json.reb]
    <markup> [https://raw.githubusercontent.com/rgchris/Scripts/master/experimental/markup.reb]
    <modflick> [https://raw.githubusercontent.com/gchiu/Rebol3/master/scripts/modflick.reb]
    <mysql> [https://raw.githubusercontent.com/zsx/mysql-r3/ren-c/mysql-protocol-pre.r]
    <pop3> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-pop3.reb]
    <rebmu> [https://raw.githubusercontent.com/hostilefork/rebmu/master/rebmu.reb]
    <rem> [https://raw.githubusercontent.com/r3n/giuliolunati.renclib/master/usr/lib/r3/rem.reb]
    <rest> [https://raw.githubusercontent.com/rgchris/Scripts/master/experimental/rest.reb]
    <rsp> [https://raw.githubusercontent.com/rgchris/Scripts/master/ren-c/rsp.reb]
    <send> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-send.reb]
    <smtp> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-smtp.reb]
    <synctcp> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-synctcp.reb]
    <trello> [http://codeconscious.com/rebol-scripts/trello.r]
    <twitter> [https://raw.githubusercontent.com/gchiu/rebolbot/master/twitter.r3]
    <upgrade> [https://raw.githubusercontent.com/gchiu/rebol-misc/master/upgrade.reb]
    <webform> [https://raw.githubusercontent.com/rgchris/Scripts/master/ren-c/altwebform.reb]
    <webserver> [https://raw.githubusercontent.com/r3n/renclib/master/outdated/utils/webserver.reb]
    <wordify> [https://raw.githubusercontent.com/rgchris/Scripts/master/ren-c/wordify.reb]
    <xml> [https://raw.githubusercontent.com/r3n/renclib/master/outdated/modules/xml.reb]
]
