; 'load as of Dec 2020 now turns text into a block by default. See https://forum.rebol.info/t/mold-and-load-parity/1429

    <amazon-s3> [http://reb4.me/r3/s3.reb]
    <changelog> [https://raw.githubusercontent.com/r3n/renclib/master/outdated/utils/changes.reb]
    <chat> [https://gitlab.com/Zhaoshirong/rebol-chat/-/raw/master/src/chat.reb]
    <chess> [https://gitlab.com/Zhaoshirong/rebol-chess/raw/master/create-board.reb]
    <chessb> [https://gitlab.com/Zhaoshirong/rebol-chess/raw/test-branch/create-board.reb]
    <dl-renc> [https://raw.githubusercontent.com/gchiu/Rebol3/master/scripts/dl-renc.reb]
    <docx> [https://raw.githubusercontent.com/gchiu/rebol-misc/master/create-docx.reb]
    <download-latest> [https://gist.githubusercontent.com/gchiu/b8ac8c9e1097c23ba254bf757a21aada/raw/4f21f7d9580b88755aa68e9e3593d5e944710e47/check-rebols.reb]
    <downloads> [https://dd498l1ilnrxu.cloudfront.net/code.reb]
    <editor> [https://raw.githubusercontent.com/IngoHohmann/rebol-web-scripts/master/editor.r]
    <httpd> [https://raw.githubusercontent.com/r3n/renclib/master/outdated/modules/httpd.reb]
    <json> [https://raw.githubusercontent.com/r3n/renclib/master/modules/json.reb]
    <latest-of> [https://raw.githubusercontent.com/gchiu/rebol-misc/master/latest-of.reb]
    <media> [https://raw.githubusercontent.com/BrianOtto/replpad-media/master/index.r]
    <mysql> [https://raw.githubusercontent.com/zsx/mysql-r3/ren-c/mysql-protocol-pre.r]
    <nzpower> [https://gitlab.com/Zhaoshirong/nzpower/raw/master/nzpower.reb]
    <dnzpower> [https://gitlab.com/Zhaoshirong/nzpower/raw/Development/nzpower.reb]
    <popupdemo> [https://gitlab.com/hostilefork/popupdemo/raw/master/popupdemo.reb]
    <rebmu> [https://raw.githubusercontent.com/hostilefork/rebmu/master/rebmu.reb]
    <redbol> [https://raw.githubusercontent.com/metaeducation/ren-c/master/scripts/redbol.reb]
    <send> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-send.reb]
    <smtp> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-smtp.reb]
    <static-downloads> [https://gist.githubusercontent.com/gchiu/b8ac8c9e1097c23ba254bf757a21aada/raw/4f21f7d9580b88755aa68e9e3593d5e944710e47/check-rebols.reb]
    <synctcp> [https://raw.githubusercontent.com/gchiu/Rebol3/master/protocols/prot-synctcp.reb]
    <travis> [https://gist.githubusercontent.com/gchiu/b8ac8c9e1097c23ba254bf757a21aada/raw/4f21f7d9580b88755aa68e9e3593d5e944710e47/check-rebols.reb]
    <trello> [http://codeconscious.com/rebol-scripts/trello.r]
    <twitter> [https://raw.githubusercontent.com/gchiu/rebolbot/master/twitter.r3]
    <upgrade> [https://raw.githubusercontent.com/gchiu/rebol-misc/master/upgrade.reb]
    <webform> [https://raw.githubusercontent.com/r3n/renclib/master/modules/webform.reb]
    <webserver> [https://raw.githubusercontent.com/giuliolunati/ren-c-lib/master/usr/lib/r3/utils/webserver.reb]
    <xml> [https://raw.githubusercontent.com/r3n/renclib/master/modules/xml.reb]
    
